# Generated by Django 2.2.3 on 2019-09-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretty_name', models.CharField(max_length=300)),
                ('cui', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('tui', models.CharField(max_length=20)),
                ('semantic_type', models.CharField(blank=True, max_length=200, null=True)),
                ('vocab', models.CharField(max_length=100)),
                ('synonyms', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, default='')),
                ('start_ind', models.IntegerField()),
                ('end_ind', models.IntegerField()),
                ('cui', models.CharField(max_length=100)),
                ('done', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=False)),
                ('document_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTaskValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('values', models.ManyToManyField(related_name='values', to='annotator.MetaTaskValue')),
            ],
        ),
        migrations.CreateModel(
            name='MetaAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.FloatField()),
                ('validated', models.BooleanField(choices=[(0, 'Not Validated'), (1, 'Validated')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Document')),
                ('meta_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.MetaTask')),
                ('meta_task_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.MetaTaskValue')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_doc_set', to='annotator.Project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc2set', to='annotator.DocumentSet'),
        ),
    ]
