# Generated by Django 2.2.3 on 2019-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='add_data_from',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
