# Generated by Django 2.2.3 on 2019-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20190921_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
